/**
 * Authoritative Upstox Indian Equities Instrument Registry
 * 
 * Provides verified metadata for NSE/BSE equities:
 * - Authoritative Upstox instrument_key (e.g. NSE_EQ|INE002A01018)
 * - Exchange, segment, ISIN, tick size (0.05 INR), lot size (1 for cash)
 * - Freeze quantity (exchange max per-order slice limit)
 * - Dynamic price bands / circuit limits (upper / lower circuit)
 */

export interface AuthoritativeInstrument {
  instrumentKey: string;
  tradingSymbol: string;
  companyName: string;
  exchange: 'NSE' | 'BSE';
  segment: 'NSE_EQ' | 'BSE_EQ' | 'NSE_FO' | 'BSE_FO' | string;
  isin: string;
  tickSize: number;
  lotSize: number;
  minQuantity: number;
  maxQuantity: number;
  freezeQuantity: number;
  currency: 'INR';
  lowerCircuitLimit?: number;
  upperCircuitLimit?: number;
  lastPrice?: number;
  active: boolean;
  instrumentType?: 'EQUITY' | 'FUT' | 'OPT' | 'INDEX';
  expiryDate?: string;
  strikePrice?: number;
  optionType?: 'CE' | 'PE';
  contractMultiplier?: number;
}

export class UpstoxInstrumentRegistry {
  // Master definitions for liquid Nifty 50, F&O derivatives, and major Indian equities
  private static readonly MASTER_INSTRUMENTS: Record<string, AuthoritativeInstrument> = {
    NIFTY_FUT: {
      instrumentKey: 'NSE_FO|NIFTY24SEP',
      tradingSymbol: 'NIFTY_FUT',
      companyName: 'Nifty 50 Futures',
      exchange: 'NSE',
      segment: 'NSE_FO',
      isin: 'NSE_FO_NIFTY_FUT',
      tickSize: 0.05,
      lotSize: 25,
      minQuantity: 25,
      maxQuantity: 1800,
      freezeQuantity: 1800,
      currency: 'INR',
      instrumentType: 'FUT',
      contractMultiplier: 1,
      lastPrice: 24650.0,
      active: true,
    },
    BANKNIFTY_FUT: {
      instrumentKey: 'NSE_FO|BANKNIFTY24SEP',
      tradingSymbol: 'BANKNIFTY_FUT',
      companyName: 'Bank Nifty Futures',
      exchange: 'NSE',
      segment: 'NSE_FO',
      isin: 'NSE_FO_BANKNIFTY_FUT',
      tickSize: 0.05,
      lotSize: 15,
      minQuantity: 15,
      maxQuantity: 900,
      freezeQuantity: 900,
      currency: 'INR',
      instrumentType: 'FUT',
      contractMultiplier: 1,
      lastPrice: 51200.0,
      active: true,
    },
    RELIANCE: {
      instrumentKey: 'NSE_EQ|INE002A01018',
      tradingSymbol: 'RELIANCE',
      companyName: 'Reliance Industries Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE002A01018',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 10000,
      currency: 'INR',
      lowerCircuitLimit: 950.0,
      upperCircuitLimit: 3500.0,
      lastPrice: 1300.0,
      active: true,
    },
    TCS: {
      instrumentKey: 'NSE_EQ|INE467B01029',
      tradingSymbol: 'TCS',
      companyName: 'Tata Consultancy Services Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE467B01029',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 8000,
      currency: 'INR',
      lowerCircuitLimit: 1800.0,
      upperCircuitLimit: 4400.0,
      lastPrice: 2250.0,
      active: true,
    },
    INFY: {
      instrumentKey: 'NSE_EQ|INE009A01021',
      tradingSymbol: 'INFY',
      companyName: 'Infosys Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE009A01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 15000,
      currency: 'INR',
      lowerCircuitLimit: 800.0,
      upperCircuitLimit: 2200.0,
      lastPrice: 1080.0,
      active: true,
    },
    HDFCBANK: {
      instrumentKey: 'NSE_EQ|INE040A01034',
      tradingSymbol: 'HDFCBANK',
      companyName: 'HDFC Bank Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE040A01034',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 20000,
      currency: 'INR',
      lowerCircuitLimit: 500.0,
      upperCircuitLimit: 1800.0,
      lastPrice: 710.0,
      active: true,
    },
    ICICIBANK: {
      instrumentKey: 'NSE_EQ|INE090A01021',
      tradingSymbol: 'ICICIBANK',
      companyName: 'ICICI Bank Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE090A01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 25000,
      currency: 'INR',
      lowerCircuitLimit: 1000.0,
      upperCircuitLimit: 1800.0,
      lastPrice: 1420.0,
      active: true,
    },
    SBIN: {
      instrumentKey: 'NSE_EQ|INE062A01020',
      tradingSymbol: 'SBIN',
      companyName: 'State Bank of India',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE062A01020',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 30000,
      currency: 'INR',
      lowerCircuitLimit: 700.0,
      upperCircuitLimit: 1400.0,
      lastPrice: 1005.0,
      active: true,
    },
    BHARTIARTL: {
      instrumentKey: 'NSE_EQ|INE397D01024',
      tradingSymbol: 'BHARTIARTL',
      companyName: 'Bharti Airtel Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE397D01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 20000,
      currency: 'INR',
      lowerCircuitLimit: 1400.0,
      upperCircuitLimit: 2400.0,
      lastPrice: 1835.0,
      active: true,
    },
    ITC: {
      instrumentKey: 'NSE_EQ|INE154A01025',
      tradingSymbol: 'ITC',
      companyName: 'ITC Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE154A01025',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 40000,
      currency: 'INR',
      lowerCircuitLimit: 190.0,
      upperCircuitLimit: 530.0,
      lastPrice: 265.0,
      active: true,
    },
    KOTAKBANK: {
      instrumentKey: 'NSE_EQ|INE237A01036',
      tradingSymbol: 'KOTAKBANK',
      companyName: 'Kotak Mahindra Bank Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE237A01036',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 15000,
      currency: 'INR',
      lowerCircuitLimit: 300.0,
      upperCircuitLimit: 600.0,
      lastPrice: 419.0,
      active: true,
    },
    LT: {
      instrumentKey: 'NSE_EQ|INE018A01030',
      tradingSymbol: 'LT',
      companyName: 'Larsen & Toubro Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE018A01030',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 8000,
      currency: 'INR',
      lowerCircuitLimit: 3100.0,
      upperCircuitLimit: 4800.0,
      lastPrice: 3975.0,
      active: true,
    },
    TATAMOTORS: {
      instrumentKey: 'NSE_EQ|INE155A01022',
      tradingSymbol: 'TATAMOTORS',
      companyName: 'Tata Motors Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE155A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 25000,
      currency: 'INR',
      lowerCircuitLimit: 220.0,
      upperCircuitLimit: 1100.0,
      lastPrice: 305.0,
      active: true,
    },
    MARUTI: {
      instrumentKey: 'NSE_EQ|INE585B01010',
      tradingSymbol: 'MARUTI',
      companyName: 'Maruti Suzuki India Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE585B01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 3000,
      currency: 'INR',
      lowerCircuitLimit: 11000.0,
      upperCircuitLimit: 13500.0,
      lastPrice: 12200.0,
      active: true,
    },
    SUNPHARMA: {
      instrumentKey: 'NSE_EQ|INE044A01036',
      tradingSymbol: 'SUNPHARMA',
      companyName: 'Sun Pharmaceutical Industries Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE044A01036',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 15000,
      currency: 'INR',
      lowerCircuitLimit: 1550.0,
      upperCircuitLimit: 1900.0,
      lastPrice: 1720.0,
      active: true,
    },
    TATASTEEL: {
      instrumentKey: 'NSE_EQ|INE081A01020',
      tradingSymbol: 'TATASTEEL',
      companyName: 'Tata Steel Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE081A01020',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 50000,
      currency: 'INR',
      lowerCircuitLimit: 135.0,
      upperCircuitLimit: 175.0,
      lastPrice: 155.0,
      active: true,
    },
    AXISBANK: {
      instrumentKey: 'NSE_EQ|INE238A01034',
      tradingSymbol: 'AXISBANK',
      companyName: 'Axis Bank Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE238A01034',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 20000,
      currency: 'INR',
      lowerCircuitLimit: 1080.0,
      upperCircuitLimit: 1320.0,
      lastPrice: 1200.0,
      active: true,
    },
    BAJFINANCE: {
      instrumentKey: 'NSE_EQ|INE296A01032',
      tradingSymbol: 'BAJFINANCE',
      companyName: 'Bajaj Finance Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE296A01032',
      tickSize: 0.1,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 5000,
      currency: 'INR',
      lowerCircuitLimit: 800.0,
      upperCircuitLimit: 1400.0,
      lastPrice: 1054.0,
      active: true,
    },
    TITAN: {
      instrumentKey: 'NSE_EQ|INE280A01028',
      tradingSymbol: 'TITAN',
      companyName: 'Titan Company Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE280A01028',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 5000,
      currency: 'INR',
      lowerCircuitLimit: 3000.0,
      upperCircuitLimit: 4000.0,
      lastPrice: 3500.0,
      active: true,
    },
    ASIANPAINT: {
      instrumentKey: 'NSE_EQ|INE021A01026',
      tradingSymbol: 'ASIANPAINT',
      companyName: 'Asian Paints Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE021A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 5000,
      currency: 'INR',
      lowerCircuitLimit: 2500.0,
      upperCircuitLimit: 3500.0,
      lastPrice: 3000.0,
      active: true,
    },
    WIPRO: {
      instrumentKey: 'NSE_EQ|INE075A01022',
      tradingSymbol: 'WIPRO',
      companyName: 'Wipro Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE075A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 10000,
      currency: 'INR',
      lowerCircuitLimit: 400.0,
      upperCircuitLimit: 650.0,
      lastPrice: 520.0,
      active: true,
    },
    NTPC: {
      instrumentKey: 'NSE_EQ|INE733E01010',
      tradingSymbol: 'NTPC',
      companyName: 'NTPC Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE733E01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 10000,
      currency: 'INR',
      lowerCircuitLimit: 300.0,
      upperCircuitLimit: 480.0,
      lastPrice: 390.0,
      active: true,
    },
    HINDUNILVR: {
      instrumentKey: 'NSE_EQ|INE030A01027',
      tradingSymbol: 'HINDUNILVR',
      companyName: 'Hindustan Unilever Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE030A01027',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 10000,
      currency: 'INR',
      lowerCircuitLimit: 1800.0,
      upperCircuitLimit: 3200.0,
      lastPrice: 2400.0,
      active: true,
    },
    ONGC: {
      instrumentKey: 'NSE_EQ|INE213A01029',
      tradingSymbol: 'ONGC',
      companyName: 'Oil and Natural Gas Corporation Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE213A01029',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 25000,
      currency: 'INR',
      lowerCircuitLimit: 180.0,
      upperCircuitLimit: 380.0,
      lastPrice: 250.0,
      active: true,
    },
    HAL: {
      instrumentKey: 'NSE_EQ|INE066F01020',
      tradingSymbol: 'HAL',
      companyName: 'Hindustan Aeronautics Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE066F01020',
      tickSize: 0.1,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 5000,
      currency: 'INR',
      lowerCircuitLimit: 3500.0,
      upperCircuitLimit: 6000.0,
      lastPrice: 5031.0,
      active: true,
    },
    BEL: {
      instrumentKey: 'NSE_EQ|INE263A01024',
      tradingSymbol: 'BEL',
      companyName: 'Bharat Electronics Limited',
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE263A01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 50000,
      currency: 'INR',
      lowerCircuitLimit: 220.0,
      upperCircuitLimit: 420.0,
      lastPrice: 300.0,
      active: true,
    },

    "INDUSINDBK": {
      instrumentKey: 'NSE_EQ|INE095A01012',
      tradingSymbol: 'INDUSINDBK',
      companyName: "INDUSIND BANK LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE095A01012',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1160.0,
      upperCircuitLimit: 1740.0,
      lastPrice: 1450.0,
      active: true,
    },
    "BANKBARODA": {
      instrumentKey: 'NSE_EQ|INE028A01039',
      tradingSymbol: 'BANKBARODA',
      companyName: "BANK OF BARODA",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE028A01039',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 200.0,
      upperCircuitLimit: 300.0,
      lastPrice: 250.0,
      active: true,
    },
    "PNB": {
      instrumentKey: 'NSE_EQ|INE160A01022',
      tradingSymbol: 'PNB',
      companyName: "PUNJAB NATIONAL BANK",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE160A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 88.0,
      upperCircuitLimit: 132.0,
      lastPrice: 110.0,
      active: true,
    },
    "CANBK": {
      instrumentKey: 'NSE_EQ|INE476A01022',
      tradingSymbol: 'CANBK',
      companyName: "CANARA BANK",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE476A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 84.0,
      upperCircuitLimit: 126.0,
      lastPrice: 105.0,
      active: true,
    },
    "UNIONBANK": {
      instrumentKey: 'NSE_EQ|INE692A01016',
      tradingSymbol: 'UNIONBANK',
      companyName: "UNION BANK OF INDIA",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE692A01016',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 100.0,
      upperCircuitLimit: 150.0,
      lastPrice: 125.0,
      active: true,
    },
    "IDFCFIRSTB": {
      instrumentKey: 'NSE_EQ|INE092T01019',
      tradingSymbol: 'IDFCFIRSTB',
      companyName: "IDFC FIRST BANK LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE092T01019',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 60.0,
      upperCircuitLimit: 90.0,
      lastPrice: 75.0,
      active: true,
    },
    "FEDERALBNK": {
      instrumentKey: 'NSE_EQ|INE171A01029',
      tradingSymbol: 'FEDERALBNK',
      companyName: "FEDERAL BANK LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE171A01029',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 152.0,
      upperCircuitLimit: 228.0,
      lastPrice: 190.0,
      active: true,
    },
    "BAJAJFINSV": {
      instrumentKey: 'NSE_EQ|INE918I01026',
      tradingSymbol: 'BAJAJFINSV',
      companyName: "BAJAJ FINSERV LTD.",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE918I01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1480.0,
      upperCircuitLimit: 2220.0,
      lastPrice: 1850.0,
      active: true,
    },
    "CHOLAFIN": {
      instrumentKey: 'NSE_EQ|INE121A08PJ0',
      tradingSymbol: 'CHOLAFIN',
      companyName: "CHOLAMANDALAM IN & FIN CO",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE121A08PJ0',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1240.0,
      upperCircuitLimit: 1860.0,
      lastPrice: 1550.0,
      active: true,
    },
    "SHRIRAMFIN": {
      instrumentKey: 'NSE_EQ|INE721A01047',
      tradingSymbol: 'SHRIRAMFIN',
      companyName: "SHRIRAM FINANCE LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE721A01047',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2560.0,
      upperCircuitLimit: 3840.0,
      lastPrice: 3200.0,
      active: true,
    },
    "JIOFIN": {
      instrumentKey: 'NSE_EQ|INE758E01017',
      tradingSymbol: 'JIOFIN',
      companyName: "JIO FIN SERVICES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE758E01017',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 264.0,
      upperCircuitLimit: 396.0,
      lastPrice: 330.0,
      active: true,
    },
    "MUTHOOTFIN": {
      instrumentKey: 'NSE_EQ|INE414G01012',
      tradingSymbol: 'MUTHOOTFIN',
      companyName: "MUTHOOT FINANCE LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE414G01012',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1560.0,
      upperCircuitLimit: 2340.0,
      lastPrice: 1950.0,
      active: true,
    },
    "HCLTECH": {
      instrumentKey: 'NSE_EQ|INE860A01027',
      tradingSymbol: 'HCLTECH',
      companyName: "HCL TECHNOLOGIES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE860A01027',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1400.0,
      upperCircuitLimit: 2100.0,
      lastPrice: 1750.0,
      active: true,
    },
    "TECHM": {
      instrumentKey: 'NSE_EQ|INE669C01036',
      tradingSymbol: 'TECHM',
      companyName: "TECH MAHINDRA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE669C01036',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1280.0,
      upperCircuitLimit: 1920.0,
      lastPrice: 1600.0,
      active: true,
    },
    "LTM": {
      instrumentKey: 'NSE_EQ|INE214T01019',
      tradingSymbol: 'LTM',
      companyName: "LTM LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE214T01019',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4640.0,
      upperCircuitLimit: 6960.0,
      lastPrice: 5800.0,
      active: true,
    },
    "PERSISTENT": {
      instrumentKey: 'NSE_EQ|INE262H01021',
      tradingSymbol: 'PERSISTENT',
      companyName: "PERSISTENT SYSTEMS LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE262H01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4160.0,
      upperCircuitLimit: 6240.0,
      lastPrice: 5200.0,
      active: true,
    },
    "COFORGE": {
      instrumentKey: 'NSE_EQ|INE591G01025',
      tradingSymbol: 'COFORGE',
      companyName: "COFORGE LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE591G01025',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5440.0,
      upperCircuitLimit: 8160.0,
      lastPrice: 6800.0,
      active: true,
    },
    "LTTS": {
      instrumentKey: 'NSE_EQ|INE010V01017',
      tradingSymbol: 'LTTS',
      companyName: "L&T TECHNOLOGY SER. LTD.",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE010V01017',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4480.0,
      upperCircuitLimit: 6720.0,
      lastPrice: 5600.0,
      active: true,
    },
    "MPHASIS": {
      instrumentKey: 'NSE_EQ|INE356A01018',
      tradingSymbol: 'MPHASIS',
      companyName: "MPHASIS LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE356A01018',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2320.0,
      upperCircuitLimit: 3480.0,
      lastPrice: 2900.0,
      active: true,
    },
    "TATAELXSI": {
      instrumentKey: 'NSE_EQ|INE670A01012',
      tradingSymbol: 'TATAELXSI',
      companyName: "TATA ELXSI LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE670A01012',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5920.0,
      upperCircuitLimit: 8880.0,
      lastPrice: 7400.0,
      active: true,
    },
    "KPITTECH": {
      instrumentKey: 'NSE_EQ|INE04I401011',
      tradingSymbol: 'KPITTECH',
      companyName: "KPIT TECHNOLOGIES LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE04I401011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1360.0,
      upperCircuitLimit: 2040.0,
      lastPrice: 1700.0,
      active: true,
    },
    "POWERGRID": {
      instrumentKey: 'NSE_EQ|INE752E01010',
      tradingSymbol: 'POWERGRID',
      companyName: "POWER GRID CORP. LTD.",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE752E01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 268.0,
      upperCircuitLimit: 402.0,
      lastPrice: 335.0,
      active: true,
    },
    "COALINDIA": {
      instrumentKey: 'NSE_EQ|INE522F01014',
      tradingSymbol: 'COALINDIA',
      companyName: "COAL INDIA LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE522F01014',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 392.0,
      upperCircuitLimit: 588.0,
      lastPrice: 490.0,
      active: true,
    },
    "BPCL": {
      instrumentKey: 'NSE_EQ|INE029A01011',
      tradingSymbol: 'BPCL',
      companyName: "BHARAT PETROLEUM CORP  LT",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE029A01011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 280.0,
      upperCircuitLimit: 420.0,
      lastPrice: 350.0,
      active: true,
    },
    "IOC": {
      instrumentKey: 'NSE_EQ|INE242A01010',
      tradingSymbol: 'IOC',
      companyName: "INDIAN OIL CORP LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE242A01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 140.0,
      upperCircuitLimit: 210.0,
      lastPrice: 175.0,
      active: true,
    },
    "GAIL": {
      instrumentKey: 'NSE_EQ|INE129A01019',
      tradingSymbol: 'GAIL',
      companyName: "GAIL (INDIA) LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE129A01019',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 180.0,
      upperCircuitLimit: 270.0,
      lastPrice: 225.0,
      active: true,
    },
    "ADANIGREEN": {
      instrumentKey: 'NSE_EQ|INE364U01010',
      tradingSymbol: 'ADANIGREEN',
      companyName: "ADANI GREEN ENERGY LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE364U01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1440.0,
      upperCircuitLimit: 2160.0,
      lastPrice: 1800.0,
      active: true,
    },
    "ADANIPOWER": {
      instrumentKey: 'NSE_EQ|INE814H01029',
      tradingSymbol: 'ADANIPOWER',
      companyName: "ADANI POWER LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE814H01029',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 520.0,
      upperCircuitLimit: 780.0,
      lastPrice: 650.0,
      active: true,
    },
    "TATAPOWER": {
      instrumentKey: 'NSE_EQ|INE245A01021',
      tradingSymbol: 'TATAPOWER',
      companyName: "TATA POWER CO LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE245A01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 344.0,
      upperCircuitLimit: 516.0,
      lastPrice: 430.0,
      active: true,
    },
    "NHPC": {
      instrumentKey: 'NSE_EQ|INE848E01016',
      tradingSymbol: 'NHPC',
      companyName: "NHPC LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE848E01016',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 76.0,
      upperCircuitLimit: 114.0,
      lastPrice: 95.0,
      active: true,
    },
    "M&M": {
      instrumentKey: 'NSE_EQ|INE101A01026',
      tradingSymbol: 'M&M',
      companyName: "MAHINDRA & MAHINDRA LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE101A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2240.0,
      upperCircuitLimit: 3360.0,
      lastPrice: 2800.0,
      active: true,
    },
    "BAJAJ-AUTO": {
      instrumentKey: 'NSE_EQ|INE917I01010',
      tradingSymbol: 'BAJAJ-AUTO',
      companyName: "BAJAJ AUTO LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE917I01010',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 8160.0,
      upperCircuitLimit: 12240.0,
      lastPrice: 10200.0,
      active: true,
    },
    "EICHERMOT": {
      instrumentKey: 'NSE_EQ|INE066A01021',
      tradingSymbol: 'EICHERMOT',
      companyName: "EICHER MOTORS LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE066A01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 3840.0,
      upperCircuitLimit: 5760.0,
      lastPrice: 4800.0,
      active: true,
    },
    "HEROMOTOCO": {
      instrumentKey: 'NSE_EQ|INE158A01026',
      tradingSymbol: 'HEROMOTOCO',
      companyName: "HERO MOTOCORP LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE158A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4320.0,
      upperCircuitLimit: 6480.0,
      lastPrice: 5400.0,
      active: true,
    },
    "TVSMOTOR": {
      instrumentKey: 'NSE_EQ|INE494B01023',
      tradingSymbol: 'TVSMOTOR',
      companyName: "TVS MOTOR COMPANY  LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE494B01023',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1960.0,
      upperCircuitLimit: 2940.0,
      lastPrice: 2450.0,
      active: true,
    },
    "BHARATFORG": {
      instrumentKey: 'NSE_EQ|INE465A01025',
      tradingSymbol: 'BHARATFORG',
      companyName: "BHARAT FORGE LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE465A01025',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1240.0,
      upperCircuitLimit: 1860.0,
      lastPrice: 1550.0,
      active: true,
    },
    "MOTHERSON": {
      instrumentKey: 'NSE_EQ|INE775A01035',
      tradingSymbol: 'MOTHERSON',
      companyName: "SAMVRDHNA MTHRSN INTL LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE775A01035',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 152.0,
      upperCircuitLimit: 228.0,
      lastPrice: 190.0,
      active: true,
    },
    "BOSCHLTD": {
      instrumentKey: 'NSE_EQ|INE323A01026',
      tradingSymbol: 'BOSCHLTD',
      companyName: "BOSCH LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE323A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 26400.0,
      upperCircuitLimit: 39600.0,
      lastPrice: 33000.0,
      active: true,
    },
    "MRF": {
      instrumentKey: 'NSE_EQ|INE883A01011',
      tradingSymbol: 'MRF',
      companyName: "MRF LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE883A01011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 108000.0,
      upperCircuitLimit: 162000.0,
      lastPrice: 135000.0,
      active: true,
    },
    "NESTLEIND": {
      instrumentKey: 'NSE_EQ|INE239A01024',
      tradingSymbol: 'NESTLEIND',
      companyName: "NESTLE INDIA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE239A01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2000.0,
      upperCircuitLimit: 3000.0,
      lastPrice: 2500.0,
      active: true,
    },
    "BRITANNIA": {
      instrumentKey: 'NSE_EQ|INE216A01030',
      tradingSymbol: 'BRITANNIA',
      companyName: "BRITANNIA INDUSTRIES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE216A01030',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4720.0,
      upperCircuitLimit: 7080.0,
      lastPrice: 5900.0,
      active: true,
    },
    "TATACONSUM": {
      instrumentKey: 'NSE_EQ|INE192A01025',
      tradingSymbol: 'TATACONSUM',
      companyName: "TATA CONSUMER PRODUCT LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE192A01025',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 944.0,
      upperCircuitLimit: 1416.0,
      lastPrice: 1180.0,
      active: true,
    },
    "VBL": {
      instrumentKey: 'NSE_EQ|INE200M01039',
      tradingSymbol: 'VBL',
      companyName: "VARUN BEVERAGES LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE200M01039',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 496.0,
      upperCircuitLimit: 744.0,
      lastPrice: 620.0,
      active: true,
    },
    "GODREJCP": {
      instrumentKey: 'NSE_EQ|INE102D01028',
      tradingSymbol: 'GODREJCP',
      companyName: "GODREJ CONSUMER PRODUCTS",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE102D01028',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1120.0,
      upperCircuitLimit: 1680.0,
      lastPrice: 1400.0,
      active: true,
    },
    "DABUR": {
      instrumentKey: 'NSE_EQ|INE016A01026',
      tradingSymbol: 'DABUR',
      companyName: "DABUR INDIA LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE016A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 504.0,
      upperCircuitLimit: 756.0,
      lastPrice: 630.0,
      active: true,
    },
    "MARICO": {
      instrumentKey: 'NSE_EQ|INE196A01026',
      tradingSymbol: 'MARICO',
      companyName: "MARICO LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE196A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 528.0,
      upperCircuitLimit: 792.0,
      lastPrice: 660.0,
      active: true,
    },
    "COLPAL": {
      instrumentKey: 'NSE_EQ|INE259A01022',
      tradingSymbol: 'COLPAL',
      companyName: "COLGATE PALMOLIVE LTD.",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE259A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2720.0,
      upperCircuitLimit: 4080.0,
      lastPrice: 3400.0,
      active: true,
    },
    "CIPLA": {
      instrumentKey: 'NSE_EQ|INE059A01026',
      tradingSymbol: 'CIPLA',
      companyName: "CIPLA LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE059A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1280.0,
      upperCircuitLimit: 1920.0,
      lastPrice: 1600.0,
      active: true,
    },
    "DRREDDY": {
      instrumentKey: 'NSE_EQ|INE089A01031',
      tradingSymbol: 'DRREDDY',
      companyName: "DR. REDDY S LABORATORIES",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE089A01031',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5360.0,
      upperCircuitLimit: 8040.0,
      lastPrice: 6700.0,
      active: true,
    },
    "DIVISLAB": {
      instrumentKey: 'NSE_EQ|INE361B01024',
      tradingSymbol: 'DIVISLAB',
      companyName: "DIVI S LABORATORIES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE361B01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 4160.0,
      upperCircuitLimit: 6240.0,
      lastPrice: 5200.0,
      active: true,
    },
    "APOLLOHOSP": {
      instrumentKey: 'NSE_EQ|INE437A01024',
      tradingSymbol: 'APOLLOHOSP',
      companyName: "APOLLO HOSPITALS ENTER. L",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE437A01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5520.0,
      upperCircuitLimit: 8280.0,
      lastPrice: 6900.0,
      active: true,
    },
    "MANKIND": {
      instrumentKey: 'NSE_EQ|INE634S01028',
      tradingSymbol: 'MANKIND',
      companyName: "MANKIND PHARMA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE634S01028',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2000.0,
      upperCircuitLimit: 3000.0,
      lastPrice: 2500.0,
      active: true,
    },
    "TORNTPHARM": {
      instrumentKey: 'NSE_EQ|INE685A01028',
      tradingSymbol: 'TORNTPHARM',
      companyName: "TORRENT PHARMACEUTICALS L",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE685A01028',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2640.0,
      upperCircuitLimit: 3960.0,
      lastPrice: 3300.0,
      active: true,
    },
    "LUPIN": {
      instrumentKey: 'NSE_EQ|INE326A01037',
      tradingSymbol: 'LUPIN',
      companyName: "LUPIN LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE326A01037',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1720.0,
      upperCircuitLimit: 2580.0,
      lastPrice: 2150.0,
      active: true,
    },
    "ZYDUSLIFE": {
      instrumentKey: 'NSE_EQ|INE010B01027',
      tradingSymbol: 'ZYDUSLIFE',
      companyName: "ZYDUS LIFESCIENCES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE010B01027',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 880.0,
      upperCircuitLimit: 1320.0,
      lastPrice: 1100.0,
      active: true,
    },
    "AUROPHARMA": {
      instrumentKey: 'NSE_EQ|INE406A01037',
      tradingSymbol: 'AUROPHARMA',
      companyName: "AUROBINDO PHARMA LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE406A01037',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1160.0,
      upperCircuitLimit: 1740.0,
      lastPrice: 1450.0,
      active: true,
    },
    "JSWSTEEL": {
      instrumentKey: 'NSE_EQ|INE019A01038',
      tradingSymbol: 'JSWSTEEL',
      companyName: "JSW STEEL LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE019A01038',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 776.0,
      upperCircuitLimit: 1164.0,
      lastPrice: 970.0,
      active: true,
    },
    "HINDALCO": {
      instrumentKey: 'NSE_EQ|INE038A01020',
      tradingSymbol: 'HINDALCO',
      companyName: "HINDALCO  INDUSTRIES  LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE038A01020',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 544.0,
      upperCircuitLimit: 816.0,
      lastPrice: 680.0,
      active: true,
    },
    "VEDL": {
      instrumentKey: 'NSE_EQ|INE205A01025',
      tradingSymbol: 'VEDL',
      companyName: "VEDANTA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE205A01025',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 376.0,
      upperCircuitLimit: 564.0,
      lastPrice: 470.0,
      active: true,
    },
    "JINDALSTEL": {
      instrumentKey: 'NSE_EQ|INE749A01030',
      tradingSymbol: 'JINDALSTEL',
      companyName: "JINDAL STEEL LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE749A01030',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 792.0,
      upperCircuitLimit: 1188.0,
      lastPrice: 990.0,
      active: true,
    },
    "NMDC": {
      instrumentKey: 'NSE_EQ|INE584A01023',
      tradingSymbol: 'NMDC',
      companyName: "NMDC LTD.",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE584A01023',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 176.0,
      upperCircuitLimit: 264.0,
      lastPrice: 220.0,
      active: true,
    },
    "SAIL": {
      instrumentKey: 'NSE_EQ|INE114A01011',
      tradingSymbol: 'SAIL',
      companyName: "STEEL AUTHORITY OF INDIA",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE114A01011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 108.0,
      upperCircuitLimit: 162.0,
      lastPrice: 135.0,
      active: true,
    },
    "SIEMENS": {
      instrumentKey: 'NSE_EQ|INE003A01024',
      tradingSymbol: 'SIEMENS',
      companyName: "SIEMENS LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE003A01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5680.0,
      upperCircuitLimit: 8520.0,
      lastPrice: 7100.0,
      active: true,
    },
    "ABB": {
      instrumentKey: 'NSE_EQ|INE117A01022',
      tradingSymbol: 'ABB',
      companyName: "ABB INDIA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE117A01022',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 6560.0,
      upperCircuitLimit: 9840.0,
      lastPrice: 8200.0,
      active: true,
    },
    "BHEL": {
      instrumentKey: 'NSE_EQ|INE257A01026',
      tradingSymbol: 'BHEL',
      companyName: "BHEL",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE257A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 228.0,
      upperCircuitLimit: 342.0,
      lastPrice: 285.0,
      active: true,
    },
    "HAVELLS": {
      instrumentKey: 'NSE_EQ|INE176B01034',
      tradingSymbol: 'HAVELLS',
      companyName: "HAVELLS INDIA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE176B01034',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 1480.0,
      upperCircuitLimit: 2220.0,
      lastPrice: 1850.0,
      active: true,
    },
    "POLYCAB": {
      instrumentKey: 'NSE_EQ|INE455K01017',
      tradingSymbol: 'POLYCAB',
      companyName: "POLYCAB INDIA LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE455K01017',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5280.0,
      upperCircuitLimit: 7920.0,
      lastPrice: 6600.0,
      active: true,
    },
    "TRENT": {
      instrumentKey: 'NSE_EQ|INE849A01020',
      tradingSymbol: 'TRENT',
      companyName: "TRENT LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE849A01020',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 5760.0,
      upperCircuitLimit: 8640.0,
      lastPrice: 7200.0,
      active: true,
    },
    "DMART": {
      instrumentKey: 'NSE_EQ|INE192R01011',
      tradingSymbol: 'DMART',
      companyName: "AVENUE SUPERMARTS LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE192R01011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 3840.0,
      upperCircuitLimit: 5760.0,
      lastPrice: 4800.0,
      active: true,
    },
    "INDHOTEL": {
      instrumentKey: 'NSE_EQ|INE053A01029',
      tradingSymbol: 'INDHOTEL',
      companyName: "THE INDIAN HOTELS CO. LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE053A01029',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 536.0,
      upperCircuitLimit: 804.0,
      lastPrice: 670.0,
      active: true,
    },
    "BERGEPAINT": {
      instrumentKey: 'NSE_EQ|INE463A01038',
      tradingSymbol: 'BERGEPAINT',
      companyName: "BERGER PAINTS (I) LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE463A01038',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 464.0,
      upperCircuitLimit: 696.0,
      lastPrice: 580.0,
      active: true,
    },
    "ULTRACEMCO": {
      instrumentKey: 'NSE_EQ|INE481G01011',
      tradingSymbol: 'ULTRACEMCO',
      companyName: "ULTRATECH CEMENT LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE481G01011',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 9120.0,
      upperCircuitLimit: 13680.0,
      lastPrice: 11400.0,
      active: true,
    },
    "GRASIM": {
      instrumentKey: 'NSE_EQ|INE047A01021',
      tradingSymbol: 'GRASIM',
      companyName: "GRASIM INDUSTRIES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE047A01021',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2160.0,
      upperCircuitLimit: 3240.0,
      lastPrice: 2700.0,
      active: true,
    },
    "AMBUJACEM": {
      instrumentKey: 'NSE_EQ|INE079A01024',
      tradingSymbol: 'AMBUJACEM',
      companyName: "AMBUJA CEMENTS LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE079A01024',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 504.0,
      upperCircuitLimit: 756.0,
      lastPrice: 630.0,
      active: true,
    },
    "SHREECEM": {
      instrumentKey: 'NSE_EQ|INE070A01015',
      tradingSymbol: 'SHREECEM',
      companyName: "SHREE CEMENT LIMITED",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE070A01015',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 20800.0,
      upperCircuitLimit: 31200.0,
      lastPrice: 26000.0,
      active: true,
    },
    "PIDILITIND": {
      instrumentKey: 'NSE_EQ|INE318A01026',
      tradingSymbol: 'PIDILITIND',
      companyName: "PIDILITE INDUSTRIES LTD",
      exchange: 'NSE',
      segment: 'NSE_EQ',
      isin: 'INE318A01026',
      tickSize: 0.05,
      lotSize: 1,
      minQuantity: 1,
      maxQuantity: 100000,
      freezeQuantity: 100000,
      currency: 'INR',
      lowerCircuitLimit: 2480.0,
      upperCircuitLimit: 3720.0,
      lastPrice: 3100.0,
      active: true,
    },
  };

  private static dynamicCache: Map<string, AuthoritativeInstrument> = new Map();

  /**
   * Resolves instrument by symbol, instrument_key, or ISIN.
   * Returns authoritative metadata or null if unverified.
   */
  public static get(symbolOrKey: string): AuthoritativeInstrument | null {
    const raw = symbolOrKey.trim().toUpperCase();
    
    // 1. Direct match by symbol
    if (this.MASTER_INSTRUMENTS[raw]) {
      return this.MASTER_INSTRUMENTS[raw];
    }
    if (this.dynamicCache.has(raw)) {
      return this.dynamicCache.get(raw)!;
    }

    // 2. Format with exchange prefix (e.g. NSE:RELIANCE or NSE_EQ|INE002A01018)
    let extracted = raw;
    if (raw.includes(':')) {
      extracted = raw.split(':')[1];
    } else if (raw.includes('|')) {
      extracted = raw.split('|')[1];
    }

    if (this.MASTER_INSTRUMENTS[extracted]) {
      return this.MASTER_INSTRUMENTS[extracted];
    }
    if (this.dynamicCache.has(extracted)) {
      return this.dynamicCache.get(extracted)!;
    }

    // 3. Match by ISIN or instrumentKey
    for (const inst of Object.values(this.MASTER_INSTRUMENTS)) {
      if (inst.isin === raw || inst.instrumentKey === raw || inst.isin === extracted) {
        return inst;
      }
    }

    return null;
  }

  /**
   * Registers or updates an instrument in the cache (e.g. from Upstox instrument master or live quote).
   */
  public static register(inst: AuthoritativeInstrument): void {
    this.dynamicCache.set(inst.tradingSymbol.toUpperCase(), inst);
    this.dynamicCache.set(inst.instrumentKey.toUpperCase(), inst);
  }

  /**
   * Updates dynamic circuit limits for an instrument.
   */
  public static updateCircuitLimits(
    symbol: string,
    limits: { lower: number; upper: number; lastPrice?: number }
  ): boolean {
    const inst = this.get(symbol);
    if (!inst) return false;
    inst.lowerCircuitLimit = limits.lower;
    inst.upperCircuitLimit = limits.upper;
    if (limits.lastPrice !== undefined) {
      inst.lastPrice = limits.lastPrice;
    }
    this.register(inst);
    return true;
  }

  /**
   * Returns true if the instrument is verified and recognized.
   */
  public static isVerified(symbolOrKey: string): boolean {
    return this.get(symbolOrKey) !== null;
  }

  /**
   * Returns list of all authoritative master and dynamic instruments.
   */
  public static getAll(): AuthoritativeInstrument[] {
    const map = new Map<string, AuthoritativeInstrument>();
    for (const inst of Object.values(this.MASTER_INSTRUMENTS)) {
      map.set(inst.tradingSymbol, inst);
    }
    for (const inst of this.dynamicCache.values()) {
      map.set(inst.tradingSymbol, inst);
    }
    return Array.from(map.values());
  }

  /**
   * Clears dynamic cache (used for test isolation).
   */
  public static resetForTesting(): void {
    this.dynamicCache.clear();
  }
}
