import {AppState,Asset,ASSETS} from './types';
import {indicators,portfolioValue,risk} from './trading';
export type GeminiModel={name:string;displayName?:string;description?:string;inputTokenLimit?:number;supportedGenerationMethods?:string[]};
const BASE='https://generativelanguage.googleapis.com/v1beta';
export async function listGeminiModels(apiKey:string){if(!apiKey)throw new Error('Add a Gemini API key first.');let url=`${BASE}/models?key=${encodeURIComponent(apiKey)}`;const all:GeminiModel[]=[];do{const r=await fetch(url);if(!r.ok)throw new Error(`Gemini models request failed (${r.status})`);const d=await r.json();all.push(...(d.models||[]));url=d.nextPageToken?`${BASE}/models?key=${encodeURIComponent(apiKey)}&pageToken=${encodeURIComponent(d.nextPageToken)}`:''}while(url);return all.filter(m=>m.name&&m.supportedGenerationMethods?.includes('generateContent'))}
export function context(s:AppState,markets:any){const rk=risk(s,markets);return{portfolioValue:+portfolioValue(s,markets).toFixed(2),cash:+s.cash.toFixed(2),risk:rk,assets:Object.fromEntries(ASSETS.map(a=>{const m=markets[a];return[a,{price:m?.price,change24h:m?.change24h,indicators:m?indicators(m.history):null,holding:s.positions[a]}]}))}}
async function call(model:string,key:string,contents:any[],system:string){const r=await fetch(`${BASE}/models/${model.replace(/^models\//,'')}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature:.25,maxOutputTokens:700}})});if(!r.ok)throw new Error(`Gemini request failed (${r.status})`);const d=await r.json();return d.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||''}
export async function insight(asset:Asset,s:AppState,markets:any){const ind=indicators(markets[asset].history);const fallback=`${asset} is ${ind.score>=1?'showing positive':'showing mixed'} momentum. RSI is ${ind.rsi.toFixed(0)} and recent volatility is ${(ind.vol*100).toFixed(2)}%. This analysis uses live exchange data and should be treated as a decision aid, not a guarantee.`;const fallbackResult={direction:ind.score>=1?'bullish':ind.score<=-1?'bearish':'neutral',confidence:Math.min(90,50+Math.abs(ind.score)*15),rationale:fallback,signals:[{label:'Momentum',value:ind.s10&&ind.s30&&ind.s10>ind.s30?'Bullish':'Bearish'},{label:'RSI',value:ind.rsi.toFixed(1)},{label:'24h',value:`${ind.chg>=0?'+':''}${ind.chg.toFixed(2)}%`},{label:'Volatility',value:`${(ind.vol*100).toFixed(2)}%`}]};if(!s.settings.geminiApiKey)return fallbackResult;try{const text=await call(s.settings.geminiModel,s.settings.geminiApiKey,[{role:'user',parts:[{text:`Analyze ${asset}. JSON context: ${JSON.stringify(context(s,markets))}. Return concise JSON with direction, confidence, rationale and exactly 4 signals.`}]}],'You are Lumen’s trading analytics assistant. Ground every claim in the supplied market and portfolio context. Do not promise outcomes. Return JSON only.');return JSON.parse(text.replace(/```json|```/g,'').trim())}catch{return fallbackResult}}
export async function chat(text:string,s:AppState,markets:any,history:{role:'user'|'assistant';text:string}[]){const key=s.settings.geminiApiKey;if(!key)return 'Gemini is not configured. Add your API key in Settings; local market analysis remains available.';const msgs=history.slice(-8).map(m=>({role:m.role,parts:[{text:m.text}]}));msgs.push({role:'user',parts:[{text:`${text}\nLive context: ${JSON.stringify(context(s,markets))}`}]} as any);return call(s.settings.geminiModel,key,msgs,'You are Lumen Copilot. Give concise, concrete trading analysis grounded only in the provided context. Never imply certainty or guaranteed returns.')}
