import {ASSETS,AppState,Asset,Market,Order,Side} from './types';
export const META:Record<Asset,{name:string;symbol:string}>={BTC:{name:'Bitcoin',symbol:'BTCUSDT'},ETH:{name:'Ethereum',symbol:'ETHUSDT'},SOL:{name:'Solana',symbol:'SOLUSDT'},ADA:{name:'Cardano',symbol:'ADAUSDT'}};
export const FEE=0.0008;
export const money=(n:number)=>'$'+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export function portfolioValue(s:AppState,markets:Record<Asset,Market|undefined>){return s.cash+ASSETS.reduce((sum,a)=>sum+(s.positions[a]||0)*(markets[a]?.price||0),0)}
export function positionValue(s:AppState,markets:Record<Asset,Market|undefined>,a:Asset){return (s.positions[a]||0)*(markets[a]?.price||0)}
export function returns(h:number[]){const r:number[]=[];for(let i=1;i<h.length;i++)r.push((h[i]-h[i-1])/h[i-1]);return r}
export function stdev(v:number[]){if(v.length<2)return 0;const m=v.reduce((a,b)=>a+b,0)/v.length;return Math.sqrt(v.reduce((a,b)=>a+(b-m)**2,0)/(v.length-1))}
export function sma(v:number[],p:number){if(v.length<p)return null;return v.slice(-p).reduce((a,b)=>a+b,0)/p}
export function rsi(v:number[],p=14){if(v.length<p+1)return 50;let g=0,l=0;for(let i=v.length-p;i<v.length;i++){const d=v[i]-v[i-1];d>=0?g+=d:l-=d}const ag=g/p,al=l/p;return al===0?100:100-100/(1+ag/al)}
export function indicators(h:number[]){const s10=sma(h,10),s30=sma(h,30),rr=rsi(h),vol=stdev(returns(h.slice(-20))),base=h[Math.max(0,h.length-25)],chg=base?((h[h.length-1]-base)/base)*100:0;let score=0;if(s10!=null&&s30!=null)score+=s10>s30?1:-1;if(rr>60)score++;else if(rr<40)score--;return{s10,s30,rsi:rr,vol,chg,score}}
export function risk(s:AppState,markets:Record<Asset,Market|undefined>){const value=portfolioValue(s,markets);const weights=Object.fromEntries(ASSETS.map(a=>[a,value?positionValue(s,markets,a)/value:0])) as Record<Asset,number>;const vol=ASSETS.reduce((sum,a)=>sum+weights[a]*stdev(returns((markets[a]?.history||[]).slice(-20))),0);const top=Math.max(...ASSETS.map(a=>weights[a]));const score=Math.max(4,Math.min(96,Math.round(top*100*.55+Math.min(vol*3200,45))));return{score,label:score<35?'Conservative':score<65?'Moderate':'Aggressive',weights,vol}}
export function executeOrder(s:AppState,markets:Record<Asset,Market|undefined>,side:Side,asset:Asset,amount:number,auto=false):{ok:boolean;error?:string;order?:Order}{const qty=Math.abs(Number(amount));if(!Number.isFinite(qty)||qty<=0)return{ok:false,error:'Enter a valid amount.'};const price=markets[asset]?.price||0;if(!price)return{ok:false,error:'Market price unavailable.'};const raw=price*qty;const impact=Math.min(.0004+raw/4500000,.02);const fill=side==='buy'?price*(1+impact):price*(1-impact);const notional=fill*qty;const fee=notional*FEE;if(side==='buy'){if(notional+fee>s.cash)return{ok:false,error:'Insufficient cash balance.'};s.cash-=notional+fee;s.positions[asset]+=qty}else{if(qty>s.positions[asset]+1e-9)return{ok:false,error:`Insufficient ${asset} balance.`};s.positions[asset]-=qty;s.cash+=notional-fee}const order:Order={id:crypto.randomUUID(),ts:Date.now(),side,asset,amount:qty,price:fill,fee,notional,auto,status:'filled'};s.orders=[order,...s.orders].slice(0,200);return{ok:true,order}}
